[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-fs-search"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "1"
napi-derive = "1"

[build-dependencies]
napi-build = "1"
